[project]
name = "openhands-tools-bash"
version = "1.0.0"
description = "OpenHands Bash Tool - Execute bash commands in AI agents"
requires-python = ">=3.12"
dependencies = [
    "openhands-tools-core",
    "bashlex>=0.18",
    "libtmux>=0.46.2",
]

[project.entry-points."openhands.tools"]
bash = "openhands.tools.bash:BashTool"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["openhands*"]

[tool.setuptools.package-dir]
"" = "."