repos:
  - repo: local
    hooks:
      - id: uv-format
        name: Format with uv format
        entry: uv
        args: [run, ruff, format]
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
      - id: uv-check
        name: Lint with ruff
        entry: uv
        args: [run, ruff, check, --fix]
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
      - id: pyright
        name: Type check with Pyright (strict)
        entry: uv
        args: [run, pyright]
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
