"""Utility functions for the OpenHands SDK."""

from .truncate import (
    BINARY_FILE_CONTENT_TRUNCATED_NOTICE,
    CONTENT_TRUNCATED_NOTICE,
    DEFAULT_BASH_TRUNCATE_LIMIT,
    DEFAULT_TEXT_CONTENT_LIMIT,
    DEFAULT_TRUNCATE_NOTICE,
    DIRECTORY_CONTENT_TRUNCATED_NOTICE,
    MAX_RESPONSE_LEN_CHAR,
    TEXT_FILE_CONTENT_TRUNCATED_NOTICE,
    maybe_truncate,
)


__all__ = [
    "BINARY_FILE_CONTENT_TRUNCATED_NOTICE",
    "CONTENT_TRUNCATED_NOTICE",
    "DEFAULT_BASH_TRUNCATE_LIMIT",
    "DEFAULT_TEXT_CONTENT_LIMIT",
    "DEFAULT_TRUNCATE_NOTICE",
    "DIRECTORY_CONTENT_TRUNCATED_NOTICE",
    "MAX_RESPONSE_LEN_CHAR",
    "TEXT_FILE_CONTENT_TRUNCATED_NOTICE",
    "maybe_truncate",
]
