from typing import Iterator, Protocol, TypeVar


T = TypeVar("T")


class ListLike(Protocol[T]):
    def __getitem__(self, index: int) -> T: ...
    def __iter__(self) -> Iterator[T]: ...
    def append(self, item: T) -> None: ...
    def __len__(self) -> int: ...
