[project]
name = "openhands-tools-editor"
version = "1.0.0"
description = "OpenHands File Editor Tool - Edit files with string replacement"
requires-python = ">=3.12"
dependencies = [
    "openhands-tools-core",
    "binaryornot>=0.4.4",
]

[project.entry-points."openhands.tools"]
editor = "openhands.tools.editor:FileEditorTool"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["openhands*"]

[tool.setuptools.package-dir]
"" = "."