[project]
name = "openhands-tools-core"
version = "1.0.0"
description = "OpenHands Tools Core - Plugin discovery and common utilities"
requires-python = ">=3.12"
dependencies = [
    "openhands-sdk",
    "pydantic>=2.11.7",
    "cachetools",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["openhands*"]

[tool.setuptools.package-dir]
"" = "."