---
name: Scheduled Maintenance Task

on:
    # Allow manual trigger to optionally override defaults
    workflow_dispatch:
        inputs:
            agent_script:
                description: Override default agent script (optional)
                required: false
                type: string
            prompt_location:
                description: Override default prompt location (optional)
                required: false
                type: string
            llm_model:
                description: Override default LLM model (optional)
                required: false
                type: string
            llm_base_url:
                description: Override default LLM base URL (optional)
                required: false
                type: string
    # Scheduled trigger (disabled by default, uncomment and customize as needed)
    # schedule:
    #   # Run at 2 AM UTC every day
    #   - cron: "0 2 * * *"

permissions:
    contents: write
    pull-requests: write
    issues: write

jobs:
    run-maintenance-task:
        runs-on: ubuntu-latest
        env:
            # Configuration (used for both scheduled and manual runs)
            # Manual runs can override these via workflow_dispatch inputs
            AGENT_SCRIPT_URL: >-
                https://raw.githubusercontent.com/All-Hands-AI/agent-sdk/main/examples/github_workflows/01_routine_maintenance/agent_script.py
            PROMPT_LOCATION: ''
            # Set your prompt location here (URL or file path):
            # PROMPT_LOCATION: 'https://example.com/prompts/maintenance.txt'
            LLM_MODEL: openhands/claude-sonnet-4-5-20250929
            LLM_BASE_URL: ''
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12'

            - name: Install uv
              uses: astral-sh/setup-uv@v6
              with:
                  enable-cache: true

            - name: Install dependencies
              run: uv sync --frozen --group dev

            - name: Check required configuration
              env:
                  LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
                  CONFIG_PROMPT: ${{ inputs.prompt_location || env.PROMPT_LOCATION }}
                  CONFIG_MODEL: ${{ inputs.llm_model || env.LLM_MODEL }}
                  CONFIG_BASE_URL: ${{ inputs.llm_base_url || env.LLM_BASE_URL }}
              run: |
                  if [ -z "$LLM_API_KEY" ]; then
                    echo "Error: LLM_API_KEY secret is not set."
                    exit 1
                  fi

                  if [ -z "$CONFIG_PROMPT" ]; then
                    echo "Error: PROMPT_LOCATION is not set."
                    echo "Set it in the env section of the workflow file."
                    exit 1
                  fi

                  echo "Prompt location: $CONFIG_PROMPT"
                  echo "LLM model: $CONFIG_MODEL"
                  if [ -n "$CONFIG_BASE_URL" ]; then
                    echo "LLM base URL: $CONFIG_BASE_URL"
                  fi

            - name: Run maintenance task
              env:
                  LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
                  LLM_MODEL: ${{ inputs.llm_model || env.LLM_MODEL }}
                  LLM_BASE_URL: ${{ inputs.llm_base_url || env.LLM_BASE_URL }}
                  AGENT_SCRIPT: ${{ inputs.agent_script || env.AGENT_SCRIPT_URL }}
                  PROMPT_LOCATION: ${{ inputs.prompt_location || env.PROMPT_LOCATION }}
                  PYTHONPATH: ''
              run: |
                  echo "Running agent script: $AGENT_SCRIPT"
                  echo "With prompt from: $PROMPT_LOCATION"

                  # Download script if it's a URL
                  if [[ "$AGENT_SCRIPT" =~ ^https?:// ]]; then
                    echo "Downloading agent script from URL..."
                    curl -sSL "$AGENT_SCRIPT" -o /tmp/agent_script.py
                    AGENT_SCRIPT_PATH="/tmp/agent_script.py"
                  else
                    AGENT_SCRIPT_PATH="$AGENT_SCRIPT"
                  fi

                  uv run python "$AGENT_SCRIPT_PATH" "$PROMPT_LOCATION"

            - name: Upload logs as artifact
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: maintenance-task-logs
                  path: |
                      *.log
                      output/
                  retention-days: 7
