name: Docstring Coverage (by OpenHands)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Target branch to update (default: main)"
        required: false
        default: main
  pull_request:
    types: [labeled]

jobs:
  docstrings:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'oh-docstring'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:

      - name: Improve Docstrings with OpenHands
        uses: All-Hands-AI/openhands-github-action@v1
        with:
          repository: ${{ github.repository }}
          selected-branch: ${{ github.event.inputs.branch || github.base_ref || 'main' }}
          base-url: https://app.all-hands.dev
          poll: "true"
          timeout-seconds: 3600
          poll-interval-seconds: 30
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openhands-api-key: ${{ secrets.OPENHANDS_API_KEY }}
          prompt: .github/prompts/update-docstring.md
