name: Docstring Coverage (by OpenHands)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Target branch to update (default: main)"
        required: false
        default: main
  pull_request:
    types: [labeled]

jobs:
  docstrings:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'oh-docstring'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Improve Docstrings with OpenHands
        uses: All-Hands-AI/openhands-github-action@v1
        with:
          repository: ${{ github.repository }}
          selected-branch: ${{ github.event.inputs.branch || github.base_ref || 'main' }}
          base-url: https://app.all-hands.dev
          poll: "true"
          timeout-seconds: 3600
          poll-interval-seconds: 30
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openhands-api-key: ${{ secrets.OPENHANDS_API_KEY }}
          prompt: |
            You are updating this repository to achieve 100% Python docstring coverage.

            ## Goal
            - Run: uv run interrogate openhands --fail-under 100
            - If coverage < 100%, add or improve docstrings until the command passes.
            - Make minimal, doc-only changes (no behavior changes).

            ## Docstring Style Guide
            - Use **Google-style** docstrings consistently.
            - **One-line summary:** Concise, imperative, ends with a period.
            - **Args:** Document purpose, constraints, and behavior when `None` or optional.
            - **Returns/Yields:** Describe values and conditions clearly.
            - **Raises:** Document all relevant exceptions and why they occur.
            - **Classes:** Add an **Attributes:** section for key attributes.
            - **Modules:** Include a top-level docstring with purpose, context, and usage.
            - **Examples:** Add small, runnable examples where appropriate.
            - **Quality checks:**
              - No redundant restating of type hints unless clarifying intent.
              - Keep lines ≤ 100 chars.
              - Note side effects (I/O, logging, mutation).
              - For async functions, specify concurrency/ordering assumptions.

            ## Acceptance Criteria
            - `uv run interrogate openhands --fail-under 100` passes.
            - Docstrings adhere to the style guide.
            - No functional changes; CI/tests continue to pass.
