---
# .github/workflows/precommit.yml
name: Pre-commit checks

on:
    push:
        branches: [main]
    pull_request:
        branches: ['**']

jobs:
    pre-commit:
        runs-on: blacksmith-2vcpu-ubuntu-2404

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: '3.12'

            - name: Install uv
              uses: astral-sh/setup-uv@v7

            - name: Install dependencies
              run: uv sync --frozen --group dev

            - name: Run pre-commit (all files)
              run: uv run pre-commit run --all-files
