name: Run tests
on:
  push:
    branches: ["**"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync --frozen --group dev

      - name: Install project (editable)
        run: uv pip install -e .

      - name: Run pytest
        run: uv run pytest -v --cov=openhands --cov-report=xml
