name: Run tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

permissions:
  contents: write
  pull-requests: write

jobs:
  sdk-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Detect sdk changes
        id: changed
        uses: tj-actions/changed-files@v44
        with:
          files: |
            openhands/sdk/**
            pyproject.toml
            uv.lock
            .github/workflows/tests.yml

      - name: Install uv
        if: steps.changed.outputs.any_changed == 'true'
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install deps
        if: steps.changed.outputs.any_changed == 'true'
        run: uv sync --frozen --group dev

      - name: Run sdk tests with coverage
        if: steps.changed.outputs.any_changed == 'true'
        env:
          COVERAGE_FILE: .coverage.sdk
        run: |
          CI=true timeout 10m uv run python -m pytest -vvs \
            --cov=openhands/sdk \
            --cov-report=term-missing \
            --cov-fail-under=0 \
            tests/sdk || true

      - name: Check sdk coverage file
        if: steps.changed.outputs.any_changed == 'true' && always()
        run: |
          echo "Checking for coverage file..."
          ls -la .coverage* || echo "No coverage files found"
          if [ -f .coverage.sdk ]; then
            echo "SDK coverage file exists, size: $(stat -c%s .coverage.sdk) bytes"
          else
            echo "SDK coverage file does not exist"
          fi

      - name: Upload sdk coverage
        if: steps.changed.outputs.any_changed == 'true' && always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-sdk
          path: .coverage.sdk
          if-no-files-found: warn

  tools-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Detect tools changes
        id: changed
        uses: tj-actions/changed-files@v44
        with:
          files: |
            openhands/tools/**
            pyproject.toml
            uv.lock
            .github/workflows/tests.yml
      
      - name: Install uv
        if: steps.changed.outputs.any_changed == 'true'
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install deps
        if: steps.changed.outputs.any_changed == 'true'
        run: uv sync --frozen --group dev

      - name: Run tools tests with coverage
        if: steps.changed.outputs.any_changed == 'true'
        env:
          COVERAGE_FILE: .coverage.tools
        run: |
          CI=true timeout 10m uv run python -m pytest -vvs \
            --cov=openhands/tools \
            --cov-report=term-missing \
            --cov-fail-under=0 \
            tests/tools || true

      - name: Check tools coverage file
        if: steps.changed.outputs.any_changed == 'true' && always()
        run: |
          echo "Checking for coverage file..."
          ls -la .coverage* || echo "No coverage files found"
          if [ -f .coverage.tools ]; then
            echo "Tools coverage file exists, size: $(stat -c%s .coverage.tools) bytes"
          else
            echo "Tools coverage file does not exist"
          fi

      - name: Upload tools coverage
        if: steps.changed.outputs.any_changed == 'true' && always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-tools
          path: .coverage.tools
          if-no-files-found: warn

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Detect integration changes
        id: changed
        uses: tj-actions/changed-files@v44
        with:
          files: |
            tests/**
            openhands/**
            pyproject.toml
            uv.lock
            .github/workflows/tests.yml
      
      - name: Install uv
        if: steps.changed.outputs.any_changed == 'true'
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install deps
        if: steps.changed.outputs.any_changed == 'true'
        run: uv sync --frozen --group dev

      - name: Run integration tests with coverage
        if: steps.changed.outputs.any_changed == 'true'
        env:
          COVERAGE_FILE: .coverage.integration
        run: |
          CI=true timeout 10m uv run python -m pytest -vvs \
            --basetemp="${{ runner.temp }}/pytest" \
            -o tmp_path_retention=none \
            -o tmp_path_retention_count=0 \
            --cov=openhands \
            --cov-report=term-missing \
            --cov-fail-under=0 \
            tests/integration || true

      - name: Check integration coverage file
        if: steps.changed.outputs.any_changed == 'true' && always()
        run: |
          echo "Checking for coverage file..."
          ls -la .coverage* || echo "No coverage files found"
          if [ -f .coverage.integration ]; then
            echo "Integration coverage file exists, size: $(stat -c%s .coverage.integration) bytes"
          else
            echo "Integration coverage file does not exist"
          fi

      - name: Upload integration coverage
        if: steps.changed.outputs.any_changed == 'true' && always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-integration
          path: .coverage.integration
          if-no-files-found: warn

  coverage-report:
    runs-on: ubuntu-latest
    needs: [sdk-tests, tools-tests, integration-tests]
    if: always() && github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install deps (for coverage CLI)
        run: uv sync --frozen --group dev

      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./cov
        continue-on-error: true

      - name: Combine coverage data
        run: |
          shopt -s nullglob
          files=(cov/**/.coverage*)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No coverage files found; skipping combined report."
            exit 0
          fi
          # Bring files to cwd so coverage can find them easily
          cp "${files[@]}" .
          uv run coverage combine
          uv run coverage xml -i -o coverage.xml
          uv run coverage report -m || true

      - name: Pytest coverage PR comment
        if: always()
        continue-on-error: true
        uses: MishaKav/pytest-coverage-comment@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pytest-xml-coverage-path: coverage.xml
          title: Coverage Report
          create-new-comment: false
