name: Run tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

permissions:
  contents: write
  pull-requests: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync --frozen --group dev
        
      - name: Run tests with coverage
        run: |
          CI=true uv run pytest \
            -vvxss \
            --basetemp="${{ runner.temp }}/pytest" \
            -o tmp_path_retention=none \
            -o tmp_path_retention_count=0 \
            --cov=openhands/core \
            --cov=openhands/tools \
            --cov-report=term-missing \
            openhands/core/tests openhands/tools/tests tests

      - name: Build coverage XML (separate step, lower mem)
        if: always()
        run: uv run coverage xml -i -o coverage.xml

      - name: Pytest coverage PR comment
        if: ${{ always() && github.event_name == 'pull_request' }}
        continue-on-error: true
        uses: MishaKav/pytest-coverage-comment@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pytest-xml-coverage-path: coverage.xml
          title: Coverage Report
          create-new-comment: false

